# Generated by Django 5.2.4 on 2025-08-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backendapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="last_failed_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="locked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="login_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
