# Generated by Django 5.2.4 on 2025-08-09 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "backendapp",
            "0002_customuser_last_failed_login_customuser_locked_until_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="targetphoto",
            options={"ordering": ["-uploaded_at"]},
        ),
    ]
