# Generated by Django 4.2.23 on 2025-08-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("source_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="filesource",
            name="ingestion_notified",
            field=models.BooleanField(
                default=False, help_text="Whether data ingestion service was notified"
            ),
        ),
        migrations.AddField(
            model_name="filesource",
            name="ingestion_notified_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When data ingestion service was notified",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="filesource",
            name="ingestion_response",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Response from data ingestion service",
            ),
        ),
        migrations.AlterField(
            model_name="filesource",
            name="status",
            field=models.CharField(
                choices=[
                    ("uploading", "Uploading"),
                    ("ready", "Ready"),
                    ("failed", "Failed"),
                ],
                default="uploading",
                max_length=20,
            ),
        ),
    ]
