# Generated by Django 4.2.23 on 2025-08-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("source_management", "0002_filesource_ingestion_notified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="streamsource",
            name="configuration",
            field=models.JSONField(
                blank=True, default=dict, help_text="Additional configuration as JSON"
            ),
        ),
        migrations.AddField(
            model_name="streamsource",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Whether this source is active"
            ),
        ),
        migrations.AddField(
            model_name="streamsource",
            name="zone",
            field=models.CharField(
                blank=True, help_text="Zone name for organization", max_length=100
            ),
        ),
    ]
