# Generated by Django 4.2.23 on 2025-08-21 11:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "source_management",
            "0003_streamsource_configuration_streamsource_is_active_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="camerasource",
            name="camera_audio_channels",
            field=models.IntegerField(
                blank=True, help_text="Number of audio channels", null=True
            ),
        ),
        migrations.AddField(
            model_name="camerasource",
            name="camera_audio_codec",
            field=models.CharField(
                blank=True,
                help_text="Audio codec (e.g., aac, pcm, g711)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="camerasource",
            name="camera_audio_enabled",
            field=models.BooleanField(
                default=False, help_text="Whether camera has audio capability"
            ),
        ),
        migrations.AddField(
            model_name="camerasource",
            name="camera_audio_sample_rate",
            field=models.IntegerField(
                blank=True, help_text="Audio sample rate in Hz", null=True
            ),
        ),
        migrations.AddField(
            model_name="camerasource",
            name="camera_bitrate",
            field=models.IntegerField(
                blank=True, help_text="Camera bitrate in bits per second", null=True
            ),
        ),
        migrations.AddField(
            model_name="camerasource",
            name="camera_buffer_size",
            field=models.IntegerField(
                blank=True, help_text="Buffer size in milliseconds", null=True
            ),
        ),
        migrations.AddField(
            model_name="camerasource",
            name="camera_codec",
            field=models.CharField(
                blank=True,
                help_text="Video codec (e.g., h264, h265, mjpeg)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="camerasource",
            name="camera_keepalive",
            field=models.BooleanField(
                default=True, help_text="Whether to use keepalive connections"
            ),
        ),
        migrations.AddField(
            model_name="camerasource",
            name="camera_resolution_height",
            field=models.IntegerField(
                blank=True, help_text="Camera height in pixels", null=True
            ),
        ),
        migrations.AddField(
            model_name="camerasource",
            name="camera_resolution_width",
            field=models.IntegerField(
                blank=True, help_text="Camera width in pixels", null=True
            ),
        ),
        migrations.AddField(
            model_name="camerasource",
            name="camera_retry_attempts",
            field=models.IntegerField(
                default=3, help_text="Number of retry attempts on failure"
            ),
        ),
        migrations.AddField(
            model_name="camerasource",
            name="camera_timeout",
            field=models.IntegerField(
                blank=True, help_text="Connection timeout in seconds", null=True
            ),
        ),
        migrations.AddField(
            model_name="streamsource",
            name="stream_audio_bitrate",
            field=models.IntegerField(
                blank=True, help_text="Audio bitrate in bits per second", null=True
            ),
        ),
        migrations.AddField(
            model_name="streamsource",
            name="stream_audio_channels",
            field=models.IntegerField(
                blank=True, help_text="Number of audio channels", null=True
            ),
        ),
        migrations.AddField(
            model_name="streamsource",
            name="stream_audio_codec",
            field=models.CharField(
                blank=True,
                help_text="Audio codec (e.g., aac, mp3, opus)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="streamsource",
            name="stream_audio_sample_rate",
            field=models.IntegerField(
                blank=True, help_text="Audio sample rate in Hz", null=True
            ),
        ),
        migrations.AddField(
            model_name="streamsource",
            name="stream_authentication",
            field=models.JSONField(
                blank=True, default=dict, help_text="Authentication credentials as JSON"
            ),
        ),
        migrations.AddField(
            model_name="streamsource",
            name="stream_bitrate",
            field=models.IntegerField(
                blank=True, help_text="Stream bitrate in bits per second", null=True
            ),
        ),
        migrations.AddField(
            model_name="streamsource",
            name="stream_buffer_size",
            field=models.IntegerField(
                blank=True, help_text="Buffer size in milliseconds", null=True
            ),
        ),
        migrations.AddField(
            model_name="streamsource",
            name="stream_codec",
            field=models.CharField(
                blank=True,
                help_text="Video codec (e.g., h264, h265, av1)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="streamsource",
            name="stream_fps",
            field=models.FloatField(
                blank=True,
                help_text="Stream frame rate (frames per second)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.1),
                    django.core.validators.MaxValueValidator(300),
                ],
            ),
        ),
        migrations.AddField(
            model_name="streamsource",
            name="stream_headers",
            field=models.JSONField(
                blank=True, default=dict, help_text="Custom HTTP headers as JSON"
            ),
        ),
        migrations.AddField(
            model_name="streamsource",
            name="stream_keepalive",
            field=models.BooleanField(
                default=True, help_text="Whether to use keepalive connections"
            ),
        ),
        migrations.AddField(
            model_name="streamsource",
            name="stream_resolution_height",
            field=models.IntegerField(
                blank=True, help_text="Stream height in pixels", null=True
            ),
        ),
        migrations.AddField(
            model_name="streamsource",
            name="stream_resolution_width",
            field=models.IntegerField(
                blank=True, help_text="Stream width in pixels", null=True
            ),
        ),
        migrations.AddField(
            model_name="streamsource",
            name="stream_retry_attempts",
            field=models.IntegerField(
                default=3, help_text="Number of retry attempts on failure"
            ),
        ),
        migrations.AddField(
            model_name="streamsource",
            name="stream_timeout",
            field=models.IntegerField(
                blank=True, help_text="Connection timeout in seconds", null=True
            ),
        ),
        migrations.AlterField(
            model_name="camerasource",
            name="camera_fps",
            field=models.IntegerField(
                blank=True,
                help_text="Frame rate in frames per second",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(300),
                ],
            ),
        ),
    ]
