# Generated by Django 4.2.23 on 2025-08-22 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("source_management", "0004_camerasource_camera_audio_channels_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="streamsource",
            name="stream_url",
            field=models.CharField(
                help_text="URL of the video stream (supports RTSP, RTMP, HTTP, UDP, etc.)",
                max_length=500,
            ),
        ),
    ]
