# Generated by Django 4.2.23 on 2025-08-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("source_management", "0005_change_stream_url_to_charfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="camerasource",
            name="topic_name",
            field=models.CharField(
                blank=True,
                help_text="Topic name for downstream model subscription (auto-generated for camera/stream sources)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="camerasource",
            name="topic_suffix",
            field=models.CharField(
                blank=True,
                help_text="Custom suffix for topic name (max 6 chars, no spaces, replaces * in zone.camera.*)",
                max_length=6,
            ),
        ),
        migrations.AddField(
            model_name="filesource",
            name="topic_name",
            field=models.CharField(
                blank=True,
                help_text="Topic name for downstream model subscription (auto-generated for camera/stream sources)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="streamsource",
            name="topic_name",
            field=models.CharField(
                blank=True,
                help_text="Topic name for downstream model subscription (auto-generated for camera/stream sources)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="streamsource",
            name="topic_suffix",
            field=models.CharField(
                blank=True,
                help_text="Custom suffix for topic name (max 6 chars, no spaces, replaces * in zone.camera.*)",
                max_length=6,
            ),
        ),
    ]
