# Generated by Django 4.2.23 on 2025-08-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "source_management",
            "0006_camerasource_topic_name_camerasource_topic_suffix_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="filesource",
            name="topic_name",
        ),
        migrations.AlterField(
            model_name="camerasource",
            name="topic_name",
            field=models.CharField(
                blank=True,
                help_text="Topic name for downstream model subscription (auto-generated)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="streamsource",
            name="topic_name",
            field=models.CharField(
                blank=True,
                help_text="Topic name for downstream model subscription (auto-generated)",
                max_length=100,
            ),
        ),
    ]
