# Generated by Django 4.2.23 on 2025-09-24 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("source_management", "0007_remove_filesource_topic_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="filesource",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Whether this source is active"
            ),
        ),
    ]
